http:
  port: ${PORT:-9000}
  host: ${HOST:-localhost}

admin:
  port: 9876
  host: localhost

apiEndpoints:
  admin-api:
    host: "*"
    paths: ["/admin", "/admin/*"]
  all-api:
    host: "*"
    paths: ["/api", "/api/*"]
  all-socket:
    host: "*"
    paths: ["/ws", "/ws/*"]

serviceEndpoints:
  dbdiagram-api:
    urls:
      - ${API_SERVICE01}
      - ${API_SERVICE02}
  dbdiagram-socket:
    urls:
      - ${WS_SERVICE01}
      - ${WS_SERVICE02}

policies:
  - cors
  - expression
  - proxy
  - rate-limit
  - request-logger
  - dynamic-ws-proxy
  - dynamic-proxy

pipelines:
  route-admin-api:
    apiEndpoints:
      - admin-api
    policies:
      - request-logger:
      - cors:
        - action:
            origin: "*"
            methods: "*"
      - dynamic-proxy:
        - action:
            preserveHeaderKeyCase: true
            serviceEndpoint: dbdiagram-api
            xfwd: true
            changeOrigin: true
            prependPath: true
            ignorePath: false
            stripPath: false

  route-all-socket:
    apiEndpoints:
      - all-socket
    policies:
      - request-logger:
      - dynamic-ws-proxy:
        - action:
            serviceEndpoint: dbdiagram-socket
            xfwd: true
            changeOrigin: true
            prependPath: true
            ignorePath: false
            stripPath: true
            stickyWSSession: true

  route-all-api:
    apiEndpoints:
      - all-api
    policies:
      - request-logger:
      - cors:
        - action:
            origin: "*"
            methods: "*"
      - dynamic-proxy:
        - action:
            preserveHeaderKeyCase: true
            serviceEndpoint: dbdiagram-api
            xfwd: true
            changeOrigin: true
            prependPath: true
            ignorePath: false
            stripPath: true
